// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using usermanagementAPI.Models;

namespace usermanagementAPI.Migrations
{
    [DbContext(typeof(userdetailcontext))]
    partial class userdetailcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("usermanagementAPI.Models.userdetail", b =>
                {
                    b.Property<int>("userid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("active")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("firstName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("lastName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("userid");

                    b.ToTable("userdetails");
                });
#pragma warning restore 612, 618
        }
    }
}
